// constants.js
export const categories = [
  "Salary",
  "Business",
  "Operating income",
  "Profit",
  "Utilities",
  "Food",
  "Entertainment",
  "Transport",
  "Sales",
  "Crypto",
  "Farming",
  "Fees",
  "Medical",
  "School",
  "Clothing",
  "Miscellaneous",
  "Housing",
  "Insurance",
  "Interest",
  "Marketing",
  "Travel",
  "Stock",
  "Royalties",
  "Dividends",
  "Personal",
  "Purchase",
];
